import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Container from "./components/Container";
import NavBar, { navItems } from "./components/NavBar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <header className="border-b-2 border-gray-400 bg-gradient-to-br from-purple-600 to-blue-500 flex-none">
            <Container className="sm:max-w-7xl">
              <NavBar navItems={navItems} />
            </Container>
          </header>
          <main className="flex-1">{children}</main>
          <Footer />
        </div>

        <div id="offCanvas"></div>
      </body>
    </html>
  );
}
